# Generated by Django 4.2.30 on 2026-04-26 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrichmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_total', models.PositiveIntegerField(default=0)),
                ('score_tier', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('score_breakdown', models.JSONField()),
                ('email_subject', models.TextField(blank=True)),
                ('email_body', models.TextField(blank=True)),
                ('insights', models.JSONField(default=list)),
                ('raw_enrichment', models.JSONField(default=dict)),
                ('disqualifier_flag', models.BooleanField(default=False)),
                ('disqualifier_reason', models.TextField(blank=True)),
                ('llm_reasoning', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrichments', to='leads.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
